import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Instacipelogo from "../public/instalogo.png";
import addrecipe from "../public/addinstacipe002.gif";
export default function Home() {
  return (
    <div className="bg-purple-300">
      <Head>
        <title>Instacipe| Add New Instacipe </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/instalogo.png" />
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
          crossOrigin="anonymous"
          async
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>
      <div>
        <div className="w-fit mx-auto">
          <Image src={addrecipe} alt="" height="330" />
        </div>
        <div className=" border-4 border-yellow-500 rounded-xl">
          <form>
            <div className="mt-3">
              <label
                htmlFor="formGroupExampleInput2"
                className="form-label font-semibold underline text-lg"
              >
                Title of your Instacipe
              </label>
              <input
                type="text"
                className="form-control-plaintext border-b border-b-purple-500 mt-3"
                id="formGroupExampleInput2"
                placeholder="give a short and sweet name for your instacipe and write it here as a title"
              />
            </div>
            <div className="mt-3">
              <label
                htmlFor="formGroupExampleInput2"
                className="form-label font-semibold underline text-lg"
              >
                Ingredirnts
              </label>
              <input
                type="text"
                className="form-control-plaintext border-b border-b-purple-500 mt-3"
                id="formGroupExampleInput2"
                placeholder="write name of ingredient with quantity required here and click add ingredient bellow it"
              />
              <button type="button" className="btn btn-info mt-2">
                Add ingredient
              </button>
            </div>
            <div className="input-group mt-3">
              <p className="input-group-plaintext font-semibold underline text-lg">
                Steps to do your Instacipe
              </p>
              <textarea
                className="form-control-plaintext border-b border-b-purple-500"
                aria-label="With textarea"
                placeholder="write step and click add step to add step and write further step"
              ></textarea>
              <button type="button" className="btn btn-info mt-2">
                Add Step
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
