import Head from "next/head";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import FFI1 from "../public/Food_Facts1.jpg";
import FFI3 from "../public/Food_Facts3.png";
import Pageheading from "../components/Pageheading";
export default function instasearch() {
  return (
    <div>
      <Head>
        <title>Instacipe | instasearch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/instalogo.png" />
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
          crossOrigin="anonymous"
          async
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>
      <Navbar />
      <Pageheading title="Instacipe's instaSearch" />
      <div className="my-6 border-3 border-gray-600 rounded-xl bg-purple-300 py-3 pl-11 flex flex-col w-5/6">
        <p className="text-2xl font-semibold">
          Search instant nutricious dishes according to your MOOD and faviourite
          taste
        </p>
        <span className="text-lg font-medium">
          because nutritious diet doesn&apos;t nean to compramise your mood
        </span>
      </div>
      <div className="mb-3 mx-auto">
        <label
          htmlFor="exampleFormControlTextarea1"
          className="form-label border-2 border-blue-500 px-4 py-2 rounded-xl bg-gray-300 text-lg font-medium"
        >
          Type your mood or faviourite taste here and get somthing delicious and
          nutricious for you
        </label>
        <div className="flex flex-row space-x-5">
          <div className="w-4/5 mx-5">
            <textarea
              className="form-control border-2 border-blue-500 mx-5 h-1/2"
              id="exampleFormControlTextarea1"
              rows="5"
            ></textarea>
            <button
              type="button"
              className="btn btn-warning mx-5 my-1 border-1 border-pink-500 bg-yellow-400 rounded-lg text-lg font-bold"
            >
              InstaSearch
            </button>
          </div>
          <div className="border-2 border-yellow-500 mx-5 w-9/12 rounded-3xl">
            <p className="bg-yellow-500 font-medium text-xl px-10 border-2 rounded-xl">
              Did you know...
            </p>
            <Image src={FFI3} alt="food fact here " />
          </div>
        </div>
      </div>
      <div className="my-6 border-3 border-gray-600 rounded-xl bg-purple-300 py-3 pl-11 flex flex-col w-5/6">
        <p className="text-2xl font-semibold">
          Only Few Ingredients in your hand ???
        </p>
        <span className="text-lg font-medium">
          Don&apos;t worry just type your Ingredients here to get the receipes
        </span>
      </div>
      <div className="mb-3 mx-auto">
        <label
          htmlFor="exampleFormControlTextarea1"
          className="form-label border-2 border-blue-500 px-4 py-2 rounded-xl bg-gray-300 text-lg font-medium"
        >
          Type your Ingredients here and get somthing delicious and nutricious
          for you
        </label>
        <div className="flex flex-row space-x-5">
          <div className="w-3/4 mx-5">
            <textarea
              className="form-control border-2 border-blue-500 mx-5 h-1/2"
              id="exampleFormControlTextarea1"
              rows="5"
            ></textarea>
            <button
              type="button"
              className="btn btn-warning mx-5 my-3 border-1 border-pink-500 bg-yellow-400 rounded-lg text-lg font-bold"
            >
              InstaSearch
            </button>
          </div>
          <div className="border-2 border-yellow-500 mx-5 w-9/12 pl-1 rounded-t-3xl">
            <p className="bg-yellow-500 font-medium text-xl px-10 border-2 rounded-xl">
              Did you know...
            </p>
            <Image src={FFI1} alt="food facts here " />
          </div>
        </div>
      </div>
    </div>
  );
}
