import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Instacipelogo from "../public/instalogo.png";
import fcb01 from "../public/b.png";
export default function Home() {
  return (
    <div className="bg-yellow-100">
      <Head>
        <title>Instacipe|login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/instalogo.png" />
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
          crossOrigin="anonymous"
          async
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>
      <div className="flex flex-row">
        <div className="w-1/2 border-r-4 border-purple-600">
          <Image
            src={fcb01}
            alt=""
            height="100%"
            width="100%"
            layout="responsive"
            objectFit="contain"
          />
        </div>
        <div className="w-1/2 h-fit bg-yellow-50 my-auto">
          <div className="w-fit mx-auto mt-3">
            <a href="#">
              <Image
                src={Instacipelogo}
                alt="Instacipe"
                height="100px"
                width="100px"
              />
            </a>
          </div>
          <p className="my-3 mx-auto text-4xl font-extrabold w-fit">
            Login to your Account
          </p>
          <div className="w-5/6 mx-auto ">
            <div className="mt-3 ">
              <label
                htmlFor="staticEmail"
                className="w-1/2 font-medium text-lg"
              >
                Email
              </label>
              <div className="w-1/2">
                <input
                  type="text"
                  className="form-control-plaintext border-b border-b-purple-500"
                  id="staticEmail"
                />
              </div>
            </div>
            <div className="mt-3">
              <label
                htmlFor="inputPassword"
                className="w-1/2 font-medium text-lg"
              >
                Password
              </label>
              <div className="w-1/2">
                <input
                  type="password"
                  className="form-control-plaintext border-b border-b-purple-500"
                  id="inputPassword"
                />
              </div>
            </div>

            <button
              type="button"
              className="btn w-fit mx-auto px-10 text-lg font-semibold mt-5 border-4 bg-yellow-500 border-purple-500 rounded-lg"
            >
              LOGIN
            </button>
            <div className="w-5/6 flex flex-row mt-3 space-x-5 mb-5">
              <div className="w-fit">
                <a href="#" className="text-purple-500 underline text-base">
                  Forgot Password
                </a>
              </div>
              <div className="w-fit">
                <a href="#" className="text-purple-500 underline text-base">
                  not have an account ? just create one here
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
