import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Instacipelogo from "../public/instalogo.png";
import chef_gif from "../public/chef0bgyellow.gif";
export default function Home() {
  return (
    <div className="bg-yellow-100">
      <Head>
        <title>Instacipe|sign up </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        ></link>
        <link rel="icon" href="/instalogo.png" />
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
          integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
          crossOrigin="anonymous"
          async
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
          integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
          crossOrigin="anonymous"
          async
        ></script>
      </Head>
      <div className="flex flex-row">
        <div className="h-full w-1/2 border-r-4 border-purple-500 bg-yellow-50">
          <a href="#" className="">
            <Image
              src={Instacipelogo}
              alt="instacipe"
              height={100}
              width={100}
              className=""
            />
          </a>
          <form className="mt-3">
            <div className="w-fit mx-auto mt-3 ">
              <p className="my-3 mx-auto text-3xl font-extrabold w-fit px-3">
                Create an account and share your delicous Instacipes with
                everyone
              </p>
            </div>
            <div>
              <label
                htmlFor="inputEmail4"
                className="form-label w-1/2 font-medium text-lg pl-12"
              >
                Email
              </label>
              <input
                type="email"
                className="w-1/2 form-control-plaintext border-b border-b-purple-500 ml-12"
                id="inputEmail4"
              />
            </div>
            <div className="mt-3">
              <label
                htmlFor="inputPassword4"
                className="form-label w-1/2 font-medium text-lg pl-12"
              >
                Password
              </label>
              <input
                type="password"
                className="w-1/2 form-control-plaintext border-b border-b-purple-500 ml-12"
                id="inputPassword4"
              />
            </div>
            <div className="mt-3">
              <label
                htmlFor="inputAddress"
                className="form-label w-1/2 font-medium text-lg pl-12"
              >
                Username
              </label>
              <input
                type="text"
                className="w-1/2 form-control-plaintext border-b border-b-purple-500 ml-12"
                id="inputAddress"
              />
            </div>
            <div className="input-group mt-3">
              <span className="w-full font-medium text-lg pl-12">
                First Name | last Name
              </span>
              <div className=" w-1/2 pl-12">
                <input
                  type="text"
                  aria-label="First name"
                  className="form-control-plaintext w-full border-b border-b-purple-500"
                />
                <input
                  type="text"
                  aria-label="Last name"
                  className="form-control-plaintext w-full border-b border-b-purple-500 mt-3"
                />
              </div>
            </div>
            <div className="flex flex-row mt-3">
              <button
                type="submit"
                className="btn bg-yellow-500 mx-auto px-10 text-lg font-semibold border-4 border-purple-500 rounded-lg"
              >
                Sign in
              </button>
              <div className="w-fit mr-5">
                <a href="#" className="text-purple-500 underline">
                  already have an account log in here
                </a>
              </div>
            </div>
          </form>
        </div>
        <div className="h-full w-1/2">
          <Image src={chef_gif} alt="" />
        </div>
      </div>
    </div>
  );
}
